= LISF on NCCS Discover: Quick Start Guide
Brendan McAndrew <brendan.b.mcandrew@nasa.gov>
:revnumber: 0.1
:revdate: 2021-11-11
:toc: macro
:toclevels: 1
:source-highlighter: highlightjs        // source code highlighting engine
// url attributes
:url-lis-website: https://lis.gsfc.nasa.gov
:url-lis-testcases-page: {url-lis-website}/tests/lis
:url-lis-testcases-data: https://portal.nccs.nasa.gov/lisdata_pub/Tutorials/Web_Version/
:url-lisf-docs: https://github.com/NASA-LIS/LISF/tree/master/docs
:url-lisf-github: https://github.com/NASA-LIS/LISF
:ssh-lisf-github: git@github.com:NASA-LIS/LISF.git
// module attributes
:modulefile-dir: privatemodules
:intel-modulefile: lisf_7_intel_19_1_3_304

[.normal]
This document exists to help new LIS team members and collaborators get up and running on NASA's link:https://www.nccs.nasa.gov/systems/discover[Discover] high-performance computing system. For general information about using Discover, review the link:https://www.nccs.nasa.gov/nccs-users/[user information pages] and link:https://www.nccs.nasa.gov/nccs-users/instructional/instructional-videos[instructional videos] available on NCCS' website.

IMPORTANT: You will need an NCCS account with permission to access Discover to complete this guide. If you don't have an NCCS account, complete the link:https://www.nccs.nasa.gov/nccs-users/instructional/account-set-up[account set up process] before continuing.

toc::[]

== Accessing Discover

=== Required Software

You will need an application called a link:https://en.wikipedia.org/wiki/Terminal_emulator[terminal] to access Discover:

* **Mac:** _Terminal_ (located in Applications > Utilities) or link:https://iterm2.com/[_iTerm2_]
* **Windows:** link:https://www.putty.org/[_PuTTY_] or link:https://mobaxterm.mobatek.net/download.html[_MobaXterm_]

TIP: Need a refresher on terminal/shell basics? link:http://swcarpentry.github.io/shell-novice/[Try this!]

//TODO: MobaXTerm session setup instructions

=== Connecting to Discover

Now that you have an account and the required software you are ready to connect to Discover.

In the examples that follow, the `%` symbol at the beginning of the line represents the prompt in your terminal. You do not type that when entering any of the example commands. Text following a `>` represents example output that should be returned after running a given command.

1. Open your terminal application and use a text editor to add the following to your `~/.ssh/config` file:
+
[source,text]
----
Host discover
    #LogLevel Quiet
    User <userid>
    ProxyCommand ssh login.nccs.nasa.gov direct %h
    ForwardX11 yes
    ForwardX11Trusted yes
    Protocol 2
----
+
Where `<userid>` is your NASA AUID*. This configuration file makes it easier to connect to Discover.
+
TIP: Forgot your AUID? Visit link:https://nams.nasa.gov[NAMS] and select _Your Identity_ from the Identities dropdown menu.

2. Connect, or "SSH", to Discover:
+
[source,bash]
----
% ssh discover
----
+
This command will use the information you added to `~/.ssh/config`.

3. At the `PASSCODE:` prompt, enter your 8-digit RSA key. If using the RSA app for mobile devices, the key is displayed after entering your PIN. If you are using a "hard token" (e.g., key-fob), enter your PIN + 8-digit RSA key at the prompt.

[TIP]
====
It is possible to use the 6-digit PIN associated with your PIV badge in place of your RSA key. Follow the instructions under _PIV SSH Instructions_ on link:https://www.nccs.nasa.gov/nccs-users/instructional/logging-in/bastion-host[this page] to set up PIV SSH.
====

4. If a `Host:` prompt appears, enter `discover`.

5. At the `Password:` prompt, enter your NCCS LDAP password.

If the connection is successful, a welcome message will be printed to the terminal:

[source,bash]
----
Your password will expire in X day(s).
Last login: 1 Jan 1 12:00:00 1970 from login1.nccs.nasa.gov

*******************************************************************************

Please see the NCCS website for current status:

http://www.nccs.nasa.gov/sys.status/motd.html

*******************************************************************************

<userid>@discoverNN:~>
----

You are now connected to a _login node_ on Discover!

[IMPORTANT]
====
*Login nodes* are shared among Discover users and are link:https://wiki.uiowa.edu/display/hpcdocs/Login+Node+Usage#:~:text=The%20login%20nodes%20are%20limited,your%20jobs%20should%20run%20on.["intended for basic tasks such as uploading data, managing files, compiling software, editing scripts, and checking on or managing your jobs."] Computationally intensive processes and programs _should not_ be run on login nodes because it may affect other users sharing your node. Processes that require significant resources should be run on a _compute node._

*Compute nodes* can be accessed interactively, similar to working on a login node, or "batch jobs" can be submitted to run on compute nodes in the background using the `slurm` scheduler. To learn more about using the job scheduler, visit the NCCS instructional page for link:https://www.nccs.nasa.gov/nccs-users/instructional/using-slurm[using `slurm`].
====

If you encounter any issues connecting to Discover, NCCS also provides link:https://www.nccs.nasa.gov/nccs-users/instructional/logging-in/bastion-host[these instructions] for connecting to their systems.

TIP: New to high-performance computing? link:https://hpc-carpentry.github.io/hpc-intro/[Try this tutorial!]

== Setting up your environment on Discover

In this section, you will set up your environment on Discover for compiling and running LISF software.

. Change directories to your `$HOME` directory:
+
[source,bash]
----
% cd $HOME
----

. We suggest that you start with a clean login environment. First, move your `.profile` and, assuming you are using bash, `.bashrc` files to a backup directory for safekeeping.
+
[source,bash]
----
% mkdir profile_backup
% mv .profile .bashrc profile_backup/
----
+
If your `.bashrc` file does not run any `module load` commands or set any critical environment variables like `$PATH` or `$LD_LIBRARY_PATH` then you should be safe leaving your `.bashrc` file alone.

. Using a text editor, create a new `.profile` file in your `$HOME` directory that contains:
+
[source,bash,subs="attributes"]
----
# This file is read each time a login shell is started.
if [ -n "$PS1" ]; then
    echo "" ; echo "sourcing clean .profile" ; echo ""
fi

module use --append $HOME/{modulefile-dir}
module load {intel-modulefile}

ulimit -s unlimited

if [ -n "$PS1" ]; then
    echo ""
    echo "sourced clean .profile"
    echo "--------------------"
    echo ""
fi
----
+
This file will be executed every time you log onto Discover.

. Next, you'll need to load environment variables that LISF components require to compile and run. Discover uses the link:https://www.nccs.nasa.gov/nccs-users/instructional/using-discover/miscellaneous/using-modules[modules] package to make commonly used software available to all users. We have created our own modulefiles that load an environment suitable for compiling and running LIS, LDT, and LVT. These files are available in link:{url-lisf-github}/tree/master/env/discover[the `env/discover` directory of our GitHub repository]. In this step we will download the current Intel LISF modulefile for Discover.
+
First, make a directory called `{modulefile-dir}/` in your `$HOME` directory to store the module files and change into it:
+
[source,bash,subs="attributes"]
----
% mkdir {modulefile-dir}
% cd {modulefile-dir}
----
+
Using `curl`, download the latest LISF modulefile into `{modulefile-dir}/`:
+
[source,bash,subs="attributes"]
----
% curl -O https://raw.githubusercontent.com/NASA-LIS/LISF/master/env/discover/{intel-modulefile}
----
+
IMPORTANT: LISF module files are periodically updated as the development environment evolves, check link:https://github.com/NASA-LIS/LISF/tree/master/env/discover[here] periodically to ensure you have the latest version.

. Source your new `.profile` to load the clean environment for the current session. The clean profile will be loaded automatically on connection to Discover in future.
+
[source,bash]
----
% source $HOME/.profile
----

Your LISF environment on Discover is now ready to use!

[NOTE]
====
The storage quota for your `$HOME` directory is quite small (1GB) so we suggest that you work in your `$NOBACKUP` directory which is located at `/discover/nobackup/<userid>` and has a storage quota of 5GB. You may also be allowed to work in a directory created for your project that has significantly higher storage quota.

[source,bash]
----
% cd $NOBACKUP
----

You can check the storage quota in your `$HOME` and `$NOBACKUP` directories by entering the following command:

[source,bash]
----
% showquota -h

# the -h flag will show values in "human-friendly" format (i.e., MB and GB rather than KB)
----

The output will also show the storage quota for any additional disks associated with your userid.
====

== Cloning the LISF Source Code

Complete sections 1-4 in our link:{url-lisf-docs}/working_with_github/working_with_github.adoc[Working with GitHub] guide to set up `git` and GitHub.

[TIP]
====
New to `git` and GitHub? Need a refresher?

* link:https://git-scm.com/book/en/v2[Intro to Git]
* link:https://help.github.com/en/github[GitHub Guide (Text)]
* link:https://www.youtube.com/playlist?list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-[GitHub Guide (Videos)]
====

== Compiling LISF Components

This section will provide a brief overview of the process to build the LIS executable from the source code (i.e., compiling). A more detailed explanation can be found in the link:url-lisf-docs[LIS User's Guide]. The same process is followed for LDT and LVT.

The steps below assume you have cloned the LISF repository into a working directory in your `$NOBACKUP` space or project disk.

. Change directories into the `LISF/lis` directory and run the configure script:
+
[source,bash]
----
% cd LISF/lis
% ./configure
----
+
A series of prompts will appear asking you to select your compile configuration options. To use the default setting, simply press _Enter_. To use a non-default setting, enter the appropriate option based on the prompt (i.e., _1_ to enable or _0_ to disable) and press _Enter_. For this exercise, the default settings will suffice. Again, more detailed information about these settings may be found in the link:{url-lisf-docs}[LISF documentation].
+
[source,bash]
----
Choose the following configure options:
Parallelism (0-serial, 1-dmpar, default=1):
Optimization level (-3=strict checks with warnings, -2=strict checks, -1=debug, 0,1,2,3, default=2):
Assume little/big_endian data format (1-little, 2-big, default=2):
Use GRIBAPI/ECCODES? (0-neither, 1-gribapi, 2-eccodes, default=2):
Enable AFWA-specific grib configuration settings? (1-yes, 0-no, default=0):
Use NETCDF? (1-yes, 0-no, default=1):
NETCDF version (3 or 4, default=4):
NETCDF use shuffle filter? (1-yes, 0-no, default = 1):
NETCDF use deflate filter? (1-yes, 0-no, default = 1):
NETCDF use deflate level? (1 to 9-yes, 0-no, default = 9):
Use HDF4? (1-yes, 0-no, default=1):
Use HDF5? (1-yes, 0-no, default=1):
Use HDFEOS? (1-yes, 0-no, default=1): 0   # NOTE: HDFEOS support is currently broken. Enter "0" at the prompt.
Use MINPACK? (1-yes, 0-no, default=0):
Use LIS-CRTM? (1-yes, 0-no, default=0):
Use LIS-CMEM? (1-yes, 0-no, default=0):
Use LIS-LAPACK? (1-yes, 0-no, default=0):
----

. Compile LIS:
+
[source,bash]
----
% ./compile
----
+
After entering this command you will see a lot of text scrolling by your screen as LIS compiles. This process may take 15-20 minutes and, barring any errors, will result in a file named `LIS`. If you encounter an error, check the link:{url-lisf-docs}[LISF documentation], our link:{url-lisf-github}/discussions[GitHub Discussions forum], or ask a team member for assistance.
+
Once you are comfortable with this process, you can speed up compilation by using additional threads. It is recommended that you do this on a compute node using an interactive session or by submitting a batch job. See the link:https://www.nccs.nasa.gov/nccs-users/instructional/using-slurm[NCCS' guidance on Slurm] for more information.
+
Here is an example command for requesting an interactive session on a compute node:
+
[source,bash]
----
% salloc --ntasks=1 --qos=debug
...
# Output will appear as resources are allocated and you are connected to the interactive session. This may take several minutes...
----
+
NOTE: The "debug" queue typically has a shorter wait time, but sessions have a time limit of 1 hour.
+
When you are connected to an interactive session you are placed in your `$HOME` directory with a clean environment. Before compiling you must source your `.profile` again and change directories into `LISF/lis`.
+
[source,bash]
----
% source ~/.profile
% cd $NOBACKUP/lis-test/LISF/lis
% ./compile -j 28
----
+
Note the use of the `-j` flag to specify the number of threads to use while compiling.

. If compilation completes successfully, a file named `LIS` will exist in the `lis/` directory:
+
[source,bash]
----
% ls LIS
> LIS
----
+
You have now compiled the LIS source code into an executable file based on the default configuration settings. Follow the same process to build executables for LDT and LVT.

== LISF Public Testcases

You are now ready to work through the LISF Public Testcases. These testcases will verify that your working environment is set up properly and you have successfully compiled each of the LISF components by walking you through an end-to-end "experiment" that uses LDT, LIS, and LVT.

Follow the _Public Testcase Walkthrough_ guide available in our link:{url-lisf-docs}[documentation].